### ISSUE TITLE
changing the frontend type field property doesn't change the data type

### ISSUE THREAD

**Issue by digiltd** [outeredge/magento-layout-module#7]
I set the Frontend Type to `dropdown`, saved it. Realised it wasn't what I wanted I changed it back to `text`. The text field appeared as normal, but it wouldn't save what I typed in it, it only saved `0`.

Deleting the field and adding it again as `text` first time, worked and saved fine.

**Comment by vseager** [comment]
For this reason, changing the field type probably shouldn't be allowed at all, or only allow it to be changed to a type that is compatible with the backend type chosen for that field.

**Comment by broopdias** [comment]
Fixed
https://github.com/outeredge/magento-layout-module/commit/65fb23066fdf8b572c2dbbfffdfd5f4937c3db4f
